//
//  ViewPhotosListConfigurator.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ViewPhotosListViewController: ViewPhotosListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ViewPhotosListInteractor: ViewPhotosListViewControllerOutput
{
}

extension ViewPhotosListPresenter: ViewPhotosListInteractorOutput
{
}

class ViewPhotosListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ViewPhotosListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ViewPhotosListViewController)
  {
    let router = ViewPhotosListRouter()
    router.viewController = viewController
    
    let presenter = ViewPhotosListPresenter()
    presenter.output = viewController
    
    let interactor = ViewPhotosListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
