//
//  ViewPhotosListInteractor.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotosListInteractorInput
{
  func doSomething(request: ViewPhotosList.Something.Request)
}

protocol ViewPhotosListInteractorOutput
{
  func presentSomething(response: ViewPhotosList.Something.Response)
}

class ViewPhotosListInteractor: ViewPhotosListInteractorInput
{
  var output: ViewPhotosListInteractorOutput!
  var worker: ViewPhotosListWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: ViewPhotosList.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ViewPhotosListWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ViewPhotosList.Something.Response()
    output.presentSomething(response: response)
  }
}
