//
//  ViewPhotosListPresenter.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotosListPresenterInput
{
  func presentSomething(response: ViewPhotosList.Something.Response)
}

protocol ViewPhotosListPresenterOutput: class
{
  func displaySomething(viewModel: ViewPhotosList.Something.ViewModel)
}

class ViewPhotosListPresenter: ViewPhotosListPresenterInput
{
  weak var output: ViewPhotosListPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ViewPhotosList.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ViewPhotosList.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
