//
//  ViewPhotosListViewController.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotosListViewControllerInput
{
    func displaySomething(viewModel: ViewPhotosList.Something.ViewModel)
}

protocol ViewPhotosListViewControllerOutput
{
    func doSomething(request: ViewPhotosList.Something.Request)
}

class ViewPhotosListViewController: UICollectionViewController, ViewPhotosListViewControllerInput
{
    var output: ViewPhotosListViewControllerOutput!
    var router: ViewPhotosListRouter!
    
    fileprivate let photoCellReuseIdentifier = "PhotoCell"
    fileprivate let sectionInsets = UIEdgeInsets(top: 50.0, left: 20.0, bottom: 50.0, right: 20.0)
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ViewPhotosListConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: - Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = ViewPhotosList.Something.Request()
        output.doSomething(request: request)
    }
    
    // MARK: - Display logic
    
    func displaySomething(viewModel: ViewPhotosList.Something.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}
