//
//  ViewPhotosListModels.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ViewPhotos {
    struct SearchPhotos {
        struct Request {
            var searchTerm : String
        }
        
        struct Response {
            var searchResults : SearchResults?
            var error : NSError?
        }
        
        struct SearchResults {
            let searchTerm : String
            let resultPhotos : [Photo]
        }
    }
    
    struct ShowPhotoDetail {
        struct Request {
            var sourceURLString : String
        }
        
        struct Response {
            var sourceImage : UIImage?
            var error : NSError?
        }
    }
}


