//
//  ViewPhotosListRouter.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotosRouterInput {
    func showAlertForError(_ error: NSError)
}

class ViewPhotosRouter: ViewPhotosRouterInput {
    weak var viewController: ViewPhotosViewController!
    
    // MARK: - Navigation
    
    func showAlertForError(_ error: NSError) {
        let alertController = AlertFactory.createAlertWithError(error)
        viewController.present(alertController, animated: true, completion: nil)
    }
    
    // MARK: - Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
        //    if segue.identifier == "ShowSomewhereScene" {
        //      passDataToSomewhereScene(segue: segue)
        //    }
    }
    
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
