//
//  ViewPhotosListConfigurator.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ViewPhotosViewController: ViewPhotosPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ViewPhotosInteractor: ViewPhotosViewControllerOutput
{
}

extension ViewPhotosPresenter: ViewPhotosInteractorOutput
{
}

class ViewPhotosConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ViewPhotosConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ViewPhotosViewController)
  {
    let router = ViewPhotosRouter()
    router.viewController = viewController
    
    let presenter = ViewPhotosPresenter()
    presenter.output = viewController
    
    let interactor = ViewPhotosInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
