//
//  ViewPhotosListInteractor.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/12/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotosInteractorInput {
  func searchPhotosForTerm(request: ViewPhotos.SearchPhotos.Request)
}

protocol ViewPhotosInteractorOutput {
  func presentPhotosFromSearch(response: ViewPhotos.SearchPhotos.Response)
}

class ViewPhotosInteractor: ViewPhotosInteractorInput {
    
  var output: ViewPhotosInteractorOutput!
  var worker: FlickrPhotosWorker!
  
  // MARK: - Business logic
  
  func searchPhotosForTerm(request: ViewPhotos.SearchPhotos.Request) {
    
    worker = FlickrPhotosWorker()
    worker.searchPhotosForTerm(request.searchTerm) {
        results, error in
        
        let response = ViewPhotos.SearchPhotos.Response(searchResults: results, error: error)
        self.output.presentPhotosFromSearch(response: response)
    }
  }
}


