//
//  ViewPhotoDetailConfigurator.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/16/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ViewPhotoDetailViewController: ViewPhotoDetailPresenterOutput
{
}

extension ViewPhotoDetailInteractor: ViewPhotoDetailViewControllerOutput
{
}

extension ViewPhotoDetailPresenter: ViewPhotoDetailInteractorOutput
{
}

class ViewPhotoDetailConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ViewPhotoDetailConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ViewPhotoDetailViewController)
  {
    let router = ViewPhotoDetailRouter()
    router.viewController = viewController
    
    let presenter = ViewPhotoDetailPresenter()
    presenter.output = viewController
    
    let interactor = ViewPhotoDetailInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
