//
//  ViewPhotoDetailRouter.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/16/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotoDetailRouterInput
{
  func dismissView()
}

class ViewPhotoDetailRouter: ViewPhotoDetailRouterInput
{
  weak var viewController: ViewPhotoDetailViewController!
  
  // MARK: - Navigation
  
  func dismissView()
  {
    
  }
}
