//
//  ViewPhotoDetailViewController.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/16/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotoDetailViewControllerInput
{
}

protocol ViewPhotoDetailViewControllerOutput
{
}

class ViewPhotoDetailViewController: UIViewController, ViewPhotoDetailViewControllerInput
{
    var output: ViewPhotoDetailViewControllerOutput!
    var router: ViewPhotoDetailRouter!
    
    var displayedPhoto : Photo?
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ViewPhotoDetailConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: - Event handling
    
    func doSomethingOnLoad()
    {
    }
    
    // MARK: - Display logic
    
    func displaySomething()
    {
    }
}
