//
//  ViewPhotoDetailRouter.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/17/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotoDetailRouterInput
{
    func showSharePopupForPhotoImage(_ photoImage: UIImage, from sender: UIBarButtonItem)
}

class ViewPhotoDetailRouter: ViewPhotoDetailRouterInput
{
  weak var viewController: ViewPhotoDetailViewController!
  
  // MARK: - Communication
  
    func showSharePopupForPhotoImage(_ photoImage: UIImage, from sender: UIBarButtonItem) {
        let shareScreen = UIActivityViewController(activityItems: [photoImage], applicationActivities: nil)
        let popoverPresentationController = shareScreen.popoverPresentationController
        popoverPresentationController?.barButtonItem = sender
        popoverPresentationController?.permittedArrowDirections = .any
        viewController.present(shareScreen, animated: true, completion: nil)
    }
}
