//
//  ViewPhotoDetailPresenter.swift
//  PhotoViewer
//
//  Created by Alex Tanabe on 11/16/16.
//  Copyright (c) 2016 Alex Tanabe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ViewPhotoDetailPresenterInput
{
  func presentSomething(response: ViewPhotoDetail.Something.Response)
}

protocol ViewPhotoDetailPresenterOutput: class
{
}

class ViewPhotoDetailPresenter: ViewPhotoDetailPresenterInput
{
  weak var output: ViewPhotoDetailPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ViewPhotoDetail.Something.Response)
  {
  }
}
